name: Java CI with Maven

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn package
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7
      with:
        archive: false
        path: |
          target/*.jar
          !target/original-*.jar
    # Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v5
